//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleaningTrackingSystemProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class basketDetail
    {
        public int basketDetailsID { get; set; }
        public string basketProductName { get; set; }
        public Nullable<decimal> basketProductPrice { get; set; }
        public Nullable<int> basketID { get; set; }
        public string basketProdcutStatus { get; set; }
    
        public virtual basket basket { get; set; }
    }
}
